### PR TITLE
Add OpenAI, Anthropic and Ollama providers

### PR DESCRIPTION
**Pull request by davidmigloz**
This PR adds support for [OpenAI](https://platform.openai.com/docs/guides/text-generation), [Anthropic](https://docs.anthropic.com/en/api/messages) and [Ollama](https://ollama.com/).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md

### CODE REVIEW

**Comment by csells** [comment]
Hey, @davidmigloz. Instead of building the dependencies for these LLMs into the AI Toolkit, how about we build out another package specifically for these and potentially other community-provided LLM providers? Maybe call it `flutter_ai_providers` or `flutter_ai_community_providers`? I'm happy to work with you on it.

**Comment by davidmigloz** [comment]
Hey @csells,

That makes sense—it's the same approach we use in LangChain.dart. We have several "single provider" packages for the most popular ones (such as `langchain_openai`, `langchain_anthropic`, `langchain_google`, etc.) with minimal dependencies. But for other less popular providers, we use a generic `langchain_community` package.

Let me know how you'd like to proceed.

**Comment by csells** [comment]
My proposal: if you start up the repo with the structure for the package(s) you'd like to produce on pub.dev and add me as a contributor, then we can work together on them. Then we can publish them with your pub.dev publisher or mine. 

I have a slight preference for a single package, at least to start. We can always split them up into others as needed.

**Comment by davidmigloz** [comment]
Sorry for the wait! @csells 

I went ahead and created the repo (you should have received an invite) with the `flutter_ai_providers` package: 
- https://github.com/davidmigloz/flutter_ai_community

I've integrated the 3 providers and added some simple tests. The package is not published yet. I'll wait for your feedback!

I'll close this PR.

**Pull request closed without merging**
